version: '3.1'

services:
  postgres:
    image: postgres:13.3
  #  restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: SuperSecret
      POSTGRES_USER: admin
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
  #  restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin4/storage
    ports:
      - 8081:80
    environment:
        PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
        PGADMIN_DEFAULT_PASSWORD: SuperSecret
      # PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
